#ifndef APPINFO_H
#define APPINFO_H

#define APPNAME "Slot Machine"

#define MAJOR_VERSION "2"
#define MINOR_VERSION "0"
#define REVISION_VERSION "0"
#define VERSION MAJOR_VERSION "." MINOR_VERSION "." REVISION_VERSION
#define APPNAME_VERSION APPNAME " v" VERSION

#endif
